[package]
name = "rustvent-of-code-24"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rustvent-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
nalgebra = "0.33.2"
nom = "7.1.3"
rayon = "1.10.0"
regex = "1.11.1"
